## Numpy Exercises Solution

## Part-A : Make use of inbuild api's

In [2]:
import numpy as np

In [3]:
np_array = np.array([[1, 2, 5, 20], [8, 0, 7, 11]])

## 1. min

In [4]:
np.min(np_array, axis=1)

array([1, 0])

In [5]:
np.min(np_array)

0

## 2. max

In [6]:
np.max(np_array, axis=1)

array([20, 11])

In [7]:
np.max(np_array)

20

## 3. mean

In [8]:
np.mean(np_array, axis=1)

array([ 7. ,  6.5])

In [9]:
np.mean(np_array)

6.75

## 4. argmin

In [10]:
np.argmin(np_array)

5

## 5. argmax

In [11]:
np.argmax(np_array)

3

## 6. linalg.solve

In [12]:
x = np.array([[2, 1], [4, 9]])
y = np.array([[10], [4]])
np.linalg.solve(x, y)

array([[ 6.14285714],
       [-2.28571429]])

## 7. flatten

In [13]:
np_array.flatten(order='C')

array([ 1,  2,  5, 20,  8,  0,  7, 11])

In [14]:
np_array.flatten(order='F')

array([ 1,  8,  2,  0,  5,  7, 20, 11])

## 8. ravel

In [15]:
np.ravel(np_array)

array([ 1,  2,  5, 20,  8,  0,  7, 11])

In [16]:
np.ravel(np_array, order='F')

array([ 1,  8,  2,  0,  5,  7, 20, 11])

## 9. dot product

In [17]:
a = np.array([[2, 1, 3], [4, 9, 5]])
b = np.array([[10], [4], [7]])
np.dot(a, b)

array([[ 45],
       [111]])

## 10. * for matrix element wise multiplication

In [18]:
mat1 = np.array([[2, 4, 1], [2, 2, 4], [0, 3, 9]])
mat2 = np.array([[5, 1, 0], [3, 4, 1], [6, 2, 2]])
mat1 * mat2

array([[10,  4,  0],
       [ 6,  8,  4],
       [ 0,  6, 18]])

## 11. arrange followed by reshape

In [19]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 12. eye/identity matrix

In [20]:
np.eye(3, 4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [21]:
np.identity(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

## sum

In [22]:
np.sum(np_array, axis=1)

array([28, 26])

In [23]:
np.sum(np_array)

54

## diag

In [24]:
np.diag(np_array)

array([1, 0])

## tril/triu

In [25]:
np.tril(np_array)

array([[1, 0, 0, 0],
       [8, 0, 0, 0]])

In [26]:
np.triu(np_array)

array([[ 1,  2,  5, 20],
       [ 0,  0,  7, 11]])

## Part-B: Own implementation of numpy api's

## 1. min

In [28]:
def my_min(np_array):
    dim = np_array.shape
    if len(dim) < 2:
        min_num = np_array[0]
        for i in range(dim[0]):
            if np_array[i] < min_num:
                min_num = np_array[i]
    else:
        min_num = np_array[0][0]
        for i in range(dim[0]):
            for j in range(dim[1]):
                if np_array[i][j] < min_num:
                    min_num = np_array[i][j]
    return min_num

In [29]:
my_min(np_array)

0

## 2. max

In [30]:
def my_max(np_array):
    dim = np_array.shape
    if len(dim) < 2:
        max_num = np_array[0]
        for i in range(dim[0]):
            if np_array[i] > max_num:
                max_num = np_array[i]
    else:
        max_num = np_array[0][0]
        for i in range(dim[0]):
            for j in range(dim[1]):
                if np_array[i][j] > max_num:
                    max_num = np_array[i][j]
    return max_num

In [31]:
my_max(np_array)

20

## 3. mean

In [32]:
def my_mean(np_array):
    dim = np_array.shape
    _sum_=0
    _mean_=0
    if len(dim) < 2:
        for i in range(dim[0]):
            _sum_ += np_array[i]
        _mean_ = _sum_/(dim[0])
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                _sum_ += np_array[i][j]
        _mean_ = _sum_/(dim[0]*dim[1])
    return _mean_

In [33]:
my_mean(np_array)

6.75

## 4. argmin

In [34]:
def my_argmin(np_array):
    arg = 0
    dim = np_array.shape
    if len(dim) < 2:
        min_num = np_array[0]
        for i in range(dim[0]):
            if np_array[i] < min_num:
                min_num = np_array[i]
                arg = i
    else:
        min_num = np_array[0][0]
        r, c = 0, 0
        for i in range(dim[0]):
            for j in range(dim[1]):
                if np_array[i][j] < min_num:
                    min_num = np_array[i][j]
                    r = i
                    c = j
        if r==0:
            arg = c
        else:
            arg = dim[1] + c
    return arg

In [35]:
my_argmin(np_array)

5

## 5. argmax

In [36]:
def my_argmax(np_array):
    arg = 0
    dim = np_array.shape
    if len(dim) < 2:
        max_num = np_array[0]
        for i in range(dim[0]):
            if np_array[i] > max_num:
                max_num = np_array[i]
                arg = i
    else:
        max_num = np_array[0][0]
        r, c = 0, 0
        for i in range(dim[0]):
            for j in range(dim[1]):
                if np_array[i][j] > max_num:
                    max_num = np_array[i][j]
                    r = i
                    c = j
        if r==0:
            arg = c
        else:
            arg = c
            for i in range(r):
                arg += dim[i]
    return arg

In [37]:
my_argmax(np_array)

3

## 6. flatten

## 6.a flatten by row

In [38]:
def my_flatten_in_row_major(np_array):
    dim = np_array.shape
    flat_arr = []
    if len(dim) < 2:
        for i in range(dim[0]):
            flat_arr.append(np_array[i])
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                flat_arr.append(np_array[i][j])
    return np.array(flat_arr)

In [39]:
my_flatten_in_row_major(np_array)

array([ 1,  2,  5, 20,  8,  0,  7, 11])

## 6.b flatten by column

In [443]:
def my_flatten_in_column_major(np_array):
    dim = np_array.shape
    flat_arr = []
    if len(dim) < 2:
        for i in range(dim[0]):
            flat_arr.append(np_array[i])
    else:
        for i in range(dim[1]):
            for j in range(dim[0]):
                flat_arr.append(np_array[j][i])
    return np.array(flat_arr)

In [444]:
my_flatten_in_column_major(np_array)

array([ 1,  8,  2,  0,  5,  7, 20, 11])

## 7. ravel

## 7.a ravel by row

In [41]:
def my_ravel_in_row_major(np_array):
    dim = np_array.shape
    rav_arr = []
    if len(dim) < 2:
        for i in range(dim[0]):
            rav_arr.append(np_array[i])
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                rav_arr.append(np_array[i][j])
    return np.array(rav_arr)

In [42]:
my_ravel_in_row_major(np_array)

array([ 1,  2,  5, 20,  8,  0,  7, 11])

## 7.b ravel by column

In [43]:
def my_ravel_in_column_major(np_array):
    dim = np_array.shape
    rav_arr = []
    if len(dim) < 2:
        for i in range(dim[0]):
            rav_arr.append(np_array[i])
    else:
        for i in range(dim[1]):
            for j in range(dim[0]):
                rav_arr.append(np_array[j][i])
    return np.array(rav_arr)

In [44]:
my_ravel_in_column_major(np_array)

array([ 1,  8,  2,  0,  5,  7, 20, 11])

## 8. dot product

In [46]:
def my_dot(a, b):
    dot_product = []
    row_dot = []
    dim1 = a.shape
    dim2 = b.shape
    if len(dim1) < 2:
        a = a.reshape(1, dim1[0])
    if len(dim2) < 2:
        b = b.reshape(1, dim2[0])
    row1, column1 = a.shape
    row2, column2 = b.shape
    result = np.zeros((row1, column2), dtype=np.int)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
               result[i][j] += a[i][k] * b[k][j]
    return np.array(result)

In [47]:
my_dot(a, b)

array([[ 45],
       [111]])

## 9. * for matrix (Element wise multiplication)

In [48]:
def my_multiply(mat1, mat2):
    mult_mat = []
    mult_mat_row = []
    dim = mat1.shape
    if len(dim) < 2:
        for i in range(dim[0]):
            mult_mat.append(mat1[i]*mat2[i])
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                mult_mat_row.append((mat1[i][j])*(mat2[i][j]))
            mult_mat.append(mult_mat_row)
            mult_mat_row = []
    return np.mat(mult_mat)

In [49]:
my_multiply(mat1, mat2)

matrix([[10,  4,  0],
        [ 6,  8,  4],
        [ 0,  6, 18]])

## 10. arange followed by reshape

In [50]:
def my_arange(n):
    return np.array(list(range(n)))

In [51]:
def my_reshape(np_array, r, c):
    dim = np_array.shape
    my_row = []
    my_matrix = []
    count = 0
    row_count, column_count = 0, 0
    if len(dim) < 2:
        for i in range(r):
            for j in range(c):
                my_row.append(np_array[count])
                count += 1
            my_matrix.append(my_row)
            my_row = []
    else:
        for i in range(r):
            for j in range(c):
                my_row.append(np_array[row_count][column_count])
                if column_count < dim[1]-1:
                    column_count += 1
                else:
                    row_count +=1
                    column_count = 0
            my_matrix.append(my_row)
            my_row = []
    return np.array(my_matrix)

In [52]:
my_np_array = my_arange(10)

In [53]:
my_np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
my_reshape(my_np_array, 2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 11. eye/identity

In [56]:
def my_eye(r, c):
    my_mat = []
    my_row = []
    for i in range(r):
        for j in range(c):
            if i == j:
                my_row.append(1)
            else:
                my_row.append(0)
        my_mat.append(my_row)
        my_row = []
    return np.array(my_mat)

In [57]:
my_eye(4, 5)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [58]:
def my_identity(n):
    my_mat = []
    my_row = []
    for i in range(n):
        for j in range(n):
            if i == j:
                my_row.append(1)
            else:
                my_row.append(0)
        my_mat.append(my_row)
        my_row = []
    return np.array(my_mat)

In [59]:
my_identity(6)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

## 12. sum

In [62]:
def my_sum(np_array):
    dim = np_array.shape
    array_sum = 0
    if len(dim) < 2:
        for i in range(dim[[0]]):
            array_sum += np_array[i]
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                array_sum += np_array[i][j]
    return array_sum

In [63]:
my_sum(np_array)

54

## 13. diag

In [64]:
def my_diag(np_array):
    dim = np_array.shape
    diag = []
    if len(dim) < 2:
        diag.append(np_array[0])
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                if i == j:
                    diag.append(np_array[i][j])
    return np.array(diag)

In [65]:
my_diag(np_array)

array([1, 0])

## 14. tril/triu

In [66]:
def my_tril(np_array):
    dim = np_array.shape
    tril_array = []
    my_row = []
    if len(dim) < 2:
        tril_array.append(np_array[0])
        for i in range(1, dim[0]):
            tril_array.append(0)
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                if i >= j:
                    my_row.append(np_array[i][j])
                else:
                    my_row.append(0)
            tril_array.append(my_row)
            my_row = []
    return np.array(tril_array)

In [67]:
my_tril(np_array)

array([[1, 0, 0, 0],
       [8, 0, 0, 0]])

In [68]:
def my_triu(np_array):
    dim = np_array.shape
    tril_array = []
    my_row = []
    if len(dim) < 2:
        tril_array.append(np_array)
    else:
        for i in range(dim[0]):
            for j in range(dim[1]):
                if i <= j:
                    my_row.append(np_array[i][j])
                else:
                    my_row.append(0)
            tril_array.append(my_row)
            my_row = []
    return np.array(tril_array)

In [69]:
my_triu(np_array)

array([[ 1,  2,  5, 20],
       [ 0,  0,  7, 11]])